# Configuração base para o modelo Mini 16x16
model:
  image_size: 16
  patch_size: 4
  embedding_dim: 256
  ff_dim: 512
  num_layers: 4
  num_heads: 8
  dropout_rate: 0.1
  attention_dropout: 0.1
  num_colors: 16
  style_dim: 32
  use_flash_attention: true
  use_rope: true
  use_dynamic_scaling: true

training:
  batch_size: 128
  learning_rate: 3e-4
  weight_decay: 0.01
  num_epochs: 100
  warmup_steps: 1000
  gradient_clip_val: 1.0
  mixed_precision: true
  early_stopping_patience: 10
  save_interval: 1000

dataset:
  train_path: "data/train"
  val_path: "data/val"
  num_workers: 4
  augment_prob: 0.5
  cache_size: 10000

optimization:
  compile_mode: "max-autotune"
  target_throughput: 500
  max_batch_memory_gb: 4
  inference_timeout_ms: 200

logging:
  log_interval: 100
  save_dir: "checkpoints"
  tensorboard_dir: "runs"
  wandb_project: "mini-pixel-art"
  eval_metrics:
    - "edge_quality"
    - "palette_usage"
    - "style_consistency" 