dataset:
  augment_prob: 0.7
  augmentations:
  - random_flip
  - color_jitter
  - random_rotation
  cache_size: 10000
  num_workers: 4
  train_path: data/train
  val_path: data/val
logging:
  eval_metrics:
  - fid
  - inception_score
  - edge_quality
  - palette_usage
  - style_consistency
  log_interval: 100
  save_dir: checkpoints
  tensorboard_dir: runs
  use_wandb: true
  wandb_project: mini-pixel-art
losses:
  content_weight: 0.5
  pixel_weight: 0.3
  quant_weight: 1.0
  style_weight: 0.8
  temperature_init: 0.01
  temperature_max: 0.1
  temperature_min: 0.001
model:
  attention_dropout: 0.15
  dropout_rate: 0.15
  embedding_dim: 256
  ff_dim: 1024
  image_size: 16
  num_colors: 16
  num_heads: 4
  num_layers: 6
  patch_size: 2
  style_dim: 128
  use_alibi: true
  use_checkpoint: false
  use_flash_attention: false
  use_sparse_attention: false
  use_spectral_norm: true
optimization:
  compile_mode: max-autotune
  cpu_specific:
    use_onnxruntime: false
    use_pruning: true
    use_quantization: true
  gradient_accumulation_steps: 2
  inference_timeout_ms: 200
  max_batch_memory_gb: 8
  num_gpus: 2
  target_throughput: 500
  use_amp: true
  use_distributed: true
training:
  advanced_features:
    adaptive_augmentation: true
    advanced_logging: true
    enable_profiling: true
    multi_objective: true
    robust_recovery: true
  augmentation:
    adapt_interval: 100
    initial_strength: 0.5
  batch_size: 4
  dev_mode:
    cpu_optimizations: true
    reduced_logging: true
  dev_mode_settings:
    disable_attention: false
    enable_memmap: true
    enable_mkl: true
    max_cpu_threads: auto
    use_cpu_optimized_ops: true
    use_lightweight_model: true
  early_stopping_patience: 20
  gradient_accumulation_steps: 4
  gradient_clip_val: 1.0
  learning_rate: 0.0001
  metrics:
    log_interval: 100
    save_visualizations: true
  mixed_precision: false
  num_epochs: 5
  num_workers: 0
  profiling:
    memory_threshold: 0.9
    throughput_target: 100
  recovery:
    lr_backoff: 0.5
    max_retries: 3
  save_interval: 1000
  scheduler:
    min_lr: 1e-6
    type: cosine
    warmup_epochs: 5
  use_gradient_checkpointing: true
  warmup_steps: 5000
  weight_decay: 0.05
